import type { ReviewResult, Verdict } from "./types.js";

function verdictLabel(v: Verdict): string {
  switch (v) {
    case "SAFE_TO_MERGE":
      return "可合并（低风险）";
    case "REVIEW_RECOMMENDED":
      return "建议人工复核";
    case "HIGH_RISK":
      return "高风险";
    case "NO_COMMENT":
      return "不发表意见";
    default: {
      const _exhaustive: never = v;
      return _exhaustive;
    }
  }
}

export function formatMarkdown(
  result: ReviewResult,
  policySource: string | null = null,
): string {
  if (result.verdict === "NO_COMMENT") {
    return [
      "<!-- dep-second-opinion: NO_COMMENT -->",
      `**dep-second-opinion**: ${result.noCommentReason ?? "insufficient signal"}`,
      "",
      "_本机器人仅在有依赖变更且信号足够时留言。_",
    ].join("\n");
  }

  const lines: string[] = [
    "<!-- dep-second-opinion -->",
    `## 依赖第二意见：${verdictLabel(result.verdict)}`,
    "",
    `- **Verdict**: \`${result.verdict}\``,
    `- **Confidence**: ${(result.confidence * 100).toFixed(0)}%`,
    `- **Summary**: ${result.summary}`,
    `- **Policy**: ${policySource ? `\`${policySource}\`` : "built-in defaults"}`,
    "",
    "### Why this verdict",
    "",
  ];

  for (const reason of result.reasons) {
    lines.push(`- ${reason}`);
  }

  lines.push("");
  lines.push("### Changes");
  lines.push("");

  for (const item of result.changes) {
    const { change, osv, meta, notes, localScore, evidence } = item;
    lines.push(
      `#### \`${change.name}\` (${change.fromVersion ?? "∅"} → ${change.toVersion ?? "∅"})`,
    );
    lines.push(`- Section: \`${change.section}\` · bump: \`${change.bump}\` · score: ${localScore}`);
    lines.push("- Evidence:");
    for (const e of evidence) {
      lines.push(`  - ${e}`);
    }
    if (meta?.registryStatus === "package_missing") {
      lines.push(
        "- ⚠️ Registry: package **not found** on npm (possible hallucinated / slopsquat dependency)",
      );
    } else if (meta?.registryStatus === "version_missing") {
      lines.push(
        `- ⚠️ Registry: version \`${change.toVersion}\` **not published** on npm`,
      );
    }
    if (meta?.deprecated) {
      lines.push(`- ⚠️ Deprecated: ${meta.deprecated}`);
    }
    if (osv.length > 0) {
      lines.push("- OSV details:");
      for (const v of osv.slice(0, 5)) {
        lines.push(`  - [${v.id}](https://osv.dev/vulnerability/${v.id}): ${v.summary}`);
      }
    }
    for (const n of notes) {
      lines.push(`- Note: ${n}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "_Generated by **dep-second-opinion**. Opt-in only. This bot never modifies dependency files._",
  );

  return lines.join("\n");
}
