import type { ReviewResult, Verdict } from "./types.js";

function verdictLabel(v: Verdict): string {
  switch (v) {
    case "SAFE_TO_MERGE":
      return "可合并（低风险）";
    case "REVIEW_RECOMMENDED":
      return "建议人工复核";
    case "HIGH_RISK":
      return "高风险";
    case "NO_COMMENT":
      return "不发表意见";
    default: {
      const _exhaustive: never = v;
      return _exhaustive;
    }
  }
}

export function formatMarkdown(result: ReviewResult): string {
  if (result.verdict === "NO_COMMENT") {
    return [
      "<!-- dep-second-opinion: NO_COMMENT -->",
      `**dep-second-opinion**: ${result.noCommentReason ?? "insufficient signal"}`,
      "",
      "_本机器人仅在有依赖变更且信号足够时留言。_",
    ].join("\n");
  }

  const lines: string[] = [
    "<!-- dep-second-opinion -->",
    `## 依赖第二意见：${verdictLabel(result.verdict)}`,
    "",
    `- **Verdict**: \`${result.verdict}\``,
    `- **Confidence**: ${(result.confidence * 100).toFixed(0)}%`,
    `- **Summary**: ${result.summary}`,
    "",
    "### Changes",
    "",
  ];

  for (const item of result.changes) {
    const { change, osv, meta, notes, localScore } = item;
    lines.push(
      `#### \`${change.name}\` (${change.fromVersion ?? "∅"} → ${change.toVersion ?? "∅"})`,
    );
    lines.push(`- Bump: \`${change.bump}\` · local score: ${localScore}`);
    if (meta?.deprecated) {
      lines.push(`- ⚠️ Deprecated: ${meta.deprecated}`);
    }
    if (meta?.latestVersion) {
      lines.push(`- Registry latest: \`${meta.latestVersion}\``);
    }
    if (osv.length === 0) {
      lines.push("- OSV: no known vulns for **target** version");
    } else {
      lines.push("- OSV hits on target version:");
      for (const v of osv.slice(0, 5)) {
        lines.push(`  - [${v.id}](https://osv.dev/vulnerability/${v.id}): ${v.summary}`);
      }
    }
    for (const n of notes) {
      lines.push(`- Note: ${n}`);
    }
    lines.push("");
  }

  lines.push("---");
  lines.push("");
  lines.push(
    "_Generated by **dep-second-opinion**. Opt-in only. This bot never modifies dependency files._",
  );

  return lines.join("\n");
}
